DROP TABLE user_roles IF EXISTS;
DROP TABLE alcohol IF EXISTS;
DROP TABLE cigarette IF EXISTS;
DROP TABLE users IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE users
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(255)            NOT NULL,
  email            VARCHAR(255)            NOT NULL,
  password         VARCHAR(255)            NOT NULL,
  registered       TIMESTAMP DEFAULT now() NOT NULL,
  enabled          BOOLEAN DEFAULT TRUE    NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx ON USERS (email);

CREATE TABLE user_roles
(
  user_id INTEGER NOT NULL,
  role    VARCHAR(255),
  CONSTRAINT user_roles_idx UNIQUE (user_id, role),
  FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);

CREATE TABLE alcohol (
  id INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  user_id INTEGER   NOT NULL,
  goodsReceiptDate DATE NOT NULL,
  category VARCHAR(255) NOT NULL,
  productName VARCHAR(255) NOT NULL,
  liter DECIMAL NOT NULL,
  balanceOnTheFirstDayOfTheMonth INTEGER NOT NULL,
  receivedForMonth INTEGER NOT NULL,
  soldForMonth INTEGER NOT NULL,
  balanceOnTheLastDayOfTheMonth INTEGER NOT NULL,

  FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX alcohol_unique_user_goodsReceiptDate_idx ON alcohol (user_id, goodsReceiptDate)

CREATE TABLE cigarette (
  id INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  user_id INTEGER   NOT NULL,
  goodsReceiptDate DATE NOT NULL,
  category VARCHAR(255) NOT NULL,
  productName VARCHAR(255) NOT NULL,
  amount INTEGER NOT NULL,
  balanceOnTheFirstDayOfTheMonth INTEGER NOT NULL,
  receivedForMonth INTEGER NOT NULL,
  soldForMonth INTEGER NOT NULL,
  balanceOnTheLastDayOfTheMonth INTEGER NOT NULL,

  FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX cigarette_unique_user_goodsReceiptDate_idx ON cigarette (user_id, goodsReceiptDate)

CREATE TABLE product (
  id INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  user_id INTEGER   NOT NULL,
  goodsReceiptDate DATE NOT NULL,
  category VARCHAR(255) NOT NULL,
  productName VARCHAR(255) NOT NULL,
  amount INTEGER NOT NULL,
  balanceOnTheFirstDayOfTheMonth INTEGER NOT NULL,
  receivedForMonth INTEGER NOT NULL,
  soldForMonth INTEGER NOT NULL,
  balanceOnTheLastDayOfTheMonth INTEGER NOT NULL,

  FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX product_unique_user_goodsReceiptDate_idx ON product (user_id, goodsReceiptDate)